### ISSUE TITLE
PR: Kanban Board Project

### ISSUE THREAD

**Issue by zbahati** [zbahati/recipeApp#21]
# KanbanBoard 

- setup kanban board for the recipeApp project 

# Project Member: 
- Joyce Cruz
- Bahati zirimwabagabo

Link to the project Board
https://github.com/users/zbahati/projects/6/views/1

**Comment by DammyShittu** [comment]
Hi @zbahati and @balatstar,

## APPROVED 🟢

## Highlights
✔️ Descriptive tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
